# IntentGate installer for Windows (PowerShell): installs ONE signed canonical release manifest.
#
#   powershell -ExecutionPolicy Bypass -File .\install.ps1
#   $env:INTENTGATE_ENV_SEED = "C:\path\to\env"; .\install.ps1     (unattended)
#
# Same order and the same verifier as install.sh (release/release-manifest.py): manifest signature
# against the pinned IntentGate release key -> bundle integrity (no extra files, compose == render of
# the manifest) -> configuration contract -> images pulled by digest and checked -> start -> verify the
# provenance chain of the running product. There is no tag fallback. Secrets are generated by the
# verifier with a cryptographic RNG and are never printed.
#
# $env:INTENTGATE_ACCEPT_UNRELEASABLE_CANDIDATE = "1" is for the clean-room acceptance run ONLY.

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot
$Here = (Get-Location).Path
$Tool = "release/release-manifest.py"
$Man = "release-manifest.json"
$Sig = "release-manifest.json.sig"
$Contract = "release/config-contract.json"
# The release key is trusted ONLY by a fingerprint obtained OUT OF BAND (never from this folder).
$Fp = $env:INTENTGATE_RELEASE_KEY_FINGERPRINT

function Say($m)  { Write-Host $m -ForegroundColor White }
function OK($m)   { Write-Host "  OK " -ForegroundColor Green -NoNewline; Write-Host $m }
function Die($m)  { Write-Host "  X  " -ForegroundColor Red -NoNewline; Write-Host $m; exit 1 }
function Py { & $script:Python @args | Out-Host; return $LASTEXITCODE }

Say "IntentGate installer"

Say "Step 1 of 6  Prerequisites"
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Die "Docker is not installed (Docker Desktop)." }
docker compose version | Out-Null; if ($LASTEXITCODE -ne 0) { Die "The Docker Compose plugin (docker compose) is required." }
docker info | Out-Null; if ($LASTEXITCODE -ne 0) { Die "Docker is installed but not running." }
$script:Python = $null
foreach ($c in @("python3", "python", "py")) { if (Get-Command $c -ErrorAction SilentlyContinue) { $script:Python = $c; break } }
if (-not $script:Python) { Die "Python 3.8+ is required (the release verifier is a Python script)." }
OK "docker, docker compose and Python are available."

Say "Step 2 of 6  Verifying the signed release manifest"
if ($Fp -notmatch "^[0-9a-f]{64}$") { Die "Set INTENTGATE_RELEASE_KEY_FINGERPRINT to the IntentGate release-key fingerprint you received out of band." }
$Trust = @("--key-set", "release/trust/release-key-set.json", "--pinned-fingerprint", $Fp)
if (-not (Test-Path $Man)) { Die "$Man is missing: this folder is not a release bundle." }
if (-not (Test-Path $Sig) -or (Get-Item $Sig).Length -eq 0) { Die "$Sig is missing: an unsigned manifest is never installed." }
$Req = @("--require-releasable")
if ($env:INTENTGATE_ACCEPT_UNRELEASABLE_CANDIDATE -eq "1") {
  Write-Host "  !! CLEAN-ROOM CANDIDATE MODE: never use this for a customer." -ForegroundColor Yellow
  $Req = @()
}
if ((Py $Tool verify --manifest $Man --sig $Sig @Trust @Req) -ne 0) { Die "The release manifest did not verify. Nothing was started." }
OK "Manifest signature verified against the pinned IntentGate release key."

Say "Step 3 of 6  Verifying the release bundle"
if ((Py $Tool verify-bundle --manifest $Man --bundle-dir $Here) -ne 0) { Die "This folder is not exactly the signed bundle. Nothing was started." }
OK "Every file is the signed bundle's; docker-compose.yml is the manifest's digest-pinned render."

Say "Step 4 of 6  Configuration"
if ($env:INTENTGATE_ENV_SEED -and -not (Test-Path ".env")) {
  if (-not (Test-Path $env:INTENTGATE_ENV_SEED)) { Die "INTENTGATE_ENV_SEED points at a missing file." }
  Copy-Item $env:INTENTGATE_ENV_SEED ".env"
}
if ((Py $Tool config-generate --contract $Contract --env .env) -ne 0) { Die "Could not prepare .env." }
if ((Py $Tool config-validate --contract $Contract --env .env --scope compose) -ne 0) {
  Die "Configuration is incomplete or invalid (key names above; values are never printed). Edit .env and run .\install.ps1 again."
}
OK "Configuration satisfies the contract."

Say "Step 5 of 6  Pulling images by digest"
docker compose pull
if ($LASTEXITCODE -ne 0) { Die "Could not pull the images (private registry: docker login ghcr.io). There is no tag fallback." }
$refs = & $script:Python $Tool image-refs --kind compose --file docker-compose.yml
foreach ($line in $refs) {
  $ref = $line.Substring($line.IndexOf("=") + 1)
  if ($ref -notmatch "@sha256:[0-9a-f]{64}$") { Die "Image $ref is not pinned by digest (refusing)." }
  $dig = $ref.Substring($ref.IndexOf("@") + 1)
  $have = docker image inspect --format '{{join .RepoDigests "\n"}}' $ref
  if (-not ($have -match [regex]::Escape("@$dig"))) { Die "Pulled image for $ref does not carry digest $dig." }
}
OK "Every image is present locally with exactly the manifest's digest."

Say "Step 6 of 6  Starting and verifying the running product"
docker compose up -d
if ($LASTEXITCODE -ne 0) { Die "docker compose up failed." }
$deadline = (Get-Date).AddSeconds(300)
do {
  $bad = docker compose ps --format '{{.Service}} {{.Health}} {{.State}}' | Where-Object { $_ -match " (starting|unhealthy) " -or $_ -notmatch " running$" }
  if (-not $bad) { break }
  if ((Get-Date) -gt $deadline) { Die "Services not healthy in time: $bad" }
  Start-Sleep -Seconds 3
} while ($true)
OK "All services are running and healthy."
$facts = [System.IO.Path]::GetTempFileName()
try {
  if ((Py $Tool collect-facts --manifest $Man --form compose --project intentgate --install-dir $Here --contract $Contract --out $facts) -ne 0) { Die "Could not read the running install's facts." }
  if ((Py $Tool verify-install --manifest $Man --sig $Sig @Trust --contract $Contract --facts $facts) -ne 0) { Die "Provenance chain RED: the running product is NOT the signed release." }
} finally { Remove-Item $facts -ErrorAction SilentlyContinue }
OK "Provenance chain GREEN: the running product is the signed release."
